

; enum Mapsprites
MAPSPRITE_BOWIE_BASE: equ 0
MAPSPRITE_BOWIE_PROMO: equ 1

MAPSPRITE_SARAH_BASE: equ 5
MAPSPRITE_SARAH_PROMO: equ 6
MAPSPRITE_SARAH_SPECIAL: equ 7

MAPSPRITE_CHESTER_BASE: equ 10
MAPSPRITE_CHESTER_PROMO: equ 11
MAPSPRITE_CHESTER_SPECIAL: equ 12

MAPSPRITE_JAHA_BASE: equ 15
MAPSPRITE_JAHA_PROMO: equ 16
MAPSPRITE_JAHA_SPECIAL: equ 17

MAPSPRITE_KAZIN_BASE: equ 20
MAPSPRITE_KAZIN_PROMO: equ 21
MAPSPRITE_KAZIN_SPECIAL: equ 22

MAPSPRITE_SLADE_BASE: equ 25
MAPSPRITE_SLADE_PROMO: equ 26

MAPSPRITE_KIWI_BASE: equ 30
MAPSPRITE_KIWI_PROMO: equ 31
MAPSPRITE_KIWI_SPECIAL: equ 32

MAPSPRITE_PETER_BASE: equ 35
MAPSPRITE_PETER_PROMO: equ 36
MAPSPRITE_PETER_SPECIAL: equ 37

MAPSPRITE_MAY_BASE: equ 40
MAPSPRITE_MAY_PROMO: equ 41
MAPSPRITE_MAY_SPECIAL: equ 42

MAPSPRITE_GERHALT_BASE: equ 45
MAPSPRITE_GERHALT_PROMO: equ 46

MAPSPRITE_LUKE_BASE: equ 50
MAPSPRITE_LUKE_PROMO: equ 51

MAPSPRITE_RICK_BASE: equ 55
MAPSPRITE_RICK_PROMO: equ 56
MAPSPRITE_RICK_SPECIAL: equ 57

MAPSPRITE_ELRIC_BASE: equ 60
MAPSPRITE_ELRIC_PROMO: equ 61
MAPSPRITE_ELRIC_SPECIAL: equ 62

MAPSPRITE_ERIC_BASE: equ 65
MAPSPRITE_ERIC_PROMO: equ 66
MAPSPRITE_ERIC_SPECIAL: equ 67

MAPSPRITE_KARNA_BASE: equ 70
MAPSPRITE_KARNA_PROMO: equ 71
MAPSPRITE_KARNA_SPECIAL: equ 72

MAPSPRITE_RANDOLF_BASE: equ 75
MAPSPRITE_RANDOLF_PROMO: equ 76
MAPSPRITE_RANDOLF_SPECIAL: equ 77

MAPSPRITE_TYRIN_BASE: equ 80
MAPSPRITE_TYRIN_PROMO: equ 81
MAPSPRITE_TYRIN_SPECIAL: equ 82

MAPSPRITE_JANET_BASE: equ 85
MAPSPRITE_JANET_PROMO: equ 86
MAPSPRITE_JANET_SPECIAL: equ 87

MAPSPRITE_ROHDE_BASE: equ 90
MAPSPRITE_ROHDE_SPECIAL: equ 91

MAPSPRITE_HIGINS_BASE: equ 95
MAPSPRITE_HIGINS_PROMO: equ 96

MAPSPRITE_TAYA_BASE: equ 100
MAPSPRITE_TAYA_SPECIAL: equ 101

MAPSPRITE_SKREECH_BASE: equ 105
MAPSPRITE_SKREECH_PROMO: equ 106

MAPSPRITE_FRAYJA_BASE: equ 110
MAPSPRITE_FRAYJA_PROMO: equ 111

MAPSPRITE_JARO_BASE: equ 115
MAPSPRITE_JARO_SPECIAL: equ 116

MAPSPRITE_GYAN_BASE: equ 120
MAPSPRITE_GYAN_PROMO: equ 121

MAPSPRITE_SHEELA_BASE: equ 125
MAPSPRITE_SHEELA_SPECIAL: equ 126

MAPSPRITE_ZYNK_BASE: equ 130
MAPSPRITE_ZYNK_PROMO: equ 131

MAPSPRITE_CHAZ_BASE: equ 135
MAPSPRITE_CHAZ_PROMO: equ 136

MAPSPRITE_LEMON_BASE: equ 140
MAPSPRITE_LEMON_SPECIAL: equ 141

MAPSPRITE_CLAUDE_BASE: equ 145
MAPSPRITE_CLAUDE_PROMO: equ 146

MAPSPRITE_MAE_BASE: equ 150
MAPSPRITE_MAE_PROMO: equ 151

MAPSPRITE_PELLE_BASE: equ 155
MAPSPRITE_PELLE_PROMO: equ 156

MAPSPRITE_KEN_BASE: equ 160
MAPSPRITE_KEN_PROMO: equ 161

MAPSPRITE_VANKAR_BASE: equ 165
MAPSPRITE_VANKAR_PROMO: equ 166

MAPSPRITE_EARNEST_BASE: equ 170
MAPSPRITE_EARNEST_PROMO: equ 171

MAPSPRITE_ARTHUR_BASE: equ 175
MAPSPRITE_ARTHUR_PROMO: equ 176

MAPSPRITE_ADAM_BASE: equ 180
MAPSPRITE_ADAM_PROMO: equ 181

MAPSPRITE_ANRI_BASE: equ 185
MAPSPRITE_ANRI_PROMO: equ 186
MAPSPRITE_ANRI_SPECIAL: equ 187

MAPSPRITE_ALEF_BASE: equ 190
MAPSPRITE_ALEF_PROMO: equ 191

MAPSPRITE_TAO_BASE: equ 195
MAPSPRITE_TAO_PROMO: equ 196
MAPSPRITE_TAO_SPECIAL: equ 197

MAPSPRITE_LYLE_BASE: equ 200
MAPSPRITE_LYLE_PROMO: equ 201

MAPSPRITE_AMON_BASE: equ 205
MAPSPRITE_AMON_PROMO: equ 206

MAPSPRITE_BALBAROY_BASE: equ 210
MAPSPRITE_BALBAROY_PROMO: equ 211

MAPSPRITE_MAX_BASE: equ 215
MAPSPRITE_MAX_PROMO: equ 216

MAPSPRITE_DIANE_BASE: equ 220
MAPSPRITE_DIANE_PROMO: equ 221

MAPSPRITE_HANS_BASE: equ 225
MAPSPRITE_HANS_PROMO: equ 226

MAPSPRITE_KOKICHI_BASE: equ 230
MAPSPRITE_KOKICHI_PROMO: equ 231

MAPSPRITE_ZYLO_BASE: equ 235
MAPSPRITE_ZYLO_PROMO: equ 236

MAPSPRITE_BLEU_BASE: equ 240
MAPSPRITE_BLEU_PROMO: equ 241

MAPSPRITE_DOMINGO: equ 245
MAPSPRITE_DOMINGO_CD: equ 246

MAPSPRITE_GONG_BASE: equ 250
MAPSPRITE_GONG_PROMO: equ 251

MAPSPRITE_GORT_BASE: equ 255
MAPSPRITE_GORT_PROMO: equ 256

MAPSPRITE_GUNTZ_BASE: equ 260
MAPSPRITE_GUNTZ_PROMO: equ 261

MAPSPRITE_HANZOU: equ 265
MAPSPRITE_HANZOU_CD: equ 266

MAPSPRITE_KHRIS_BASE: equ 270
MAPSPRITE_KHRIS_PROMO: equ 271

MAPSPRITE_LOWE_BASE: equ 275
MAPSPRITE_LOWE_PROMO: equ 276

MAPSPRITE_LUGER_BASE: equ 280
MAPSPRITE_LUGER_PROMO: equ 281
MAPSPRITE_LUGER_CD: equ 282

MAPSPRITE_MUSASHI: equ 285
MAPSPRITE_MUSASHI_CD: equ 286

MAPSPRITE_TORASU_BASE: equ 290
MAPSPRITE_TORASU_PROMO: equ 291

MAPSPRITE_MAWLOCK: equ 295
MAPSPRITE_JOGURT: equ 296

MAPSPRITE_NICK_BASE: equ 300
MAPSPRITE_NICK_PROMO: equ 301
MAPSPRITE_NICK_SPECIAL: equ 302

MAPSPRITE_BRUCE_BASE: equ 305
MAPSPRITE_BRUCE_PROMO: equ 306

MAPSPRITE_SHADE_BASE: equ 310
MAPSPRITE_SHADE_PROMO: equ 311

MAPSPRITE_SIG_BASE: equ 315
MAPSPRITE_SIG_PROMO: equ 316

MAPSPRITE_WENDY_BASE: equ 320
MAPSPRITE_WENDY_PROMO: equ 321

MAPSPRITE_APIS_BASE: equ 325
MAPSPRITE_APIS_PROMO: equ 326

MAPSPRITE_CRAY_BASE: equ 330
MAPSPRITE_CRAY_PROMO: equ 331

MAPSPRITE_BARRY_BASE: equ 335
MAPSPRITE_BARRY_PROMO: equ 336

MAPSPRITE_STOCK_BASE: equ 340
MAPSPRITE_STOCK_PROMO: equ 341

MAPSPRITE_MAYFAIR_BASE: equ 345
MAPSPRITE_MAYFAIR_PROMO: equ 346
MAPSPRITE_MAYFAIR_SPECIAL: equ 347

MAPSPRITE_YEESHA_BASE: equ 350
MAPSPRITE_YEESHA_PROMO: equ 351

MAPSPRITE_TEDDY_BASE: equ 355
MAPSPRITE_TEDDY_PROMO: equ 356
MAPSPRITE_TEDDY_SPECIAL: equ 357

MAPSPRITE_KASHING_BASE: equ 360
MAPSPRITE_KASHING_PROMO: equ 361

MAPSPRITE_GATES: equ 365

MAPSPRITE_SHRIEK: equ 370

MAPSPRITE_VERN: equ 375

MAPSPRITE_AMIGO: equ 380

MAPSPRITE_DEANNA_BASE: equ 385
MAPSPRITE_DEANNA_PROMO: equ 386

MAPSPRITE_NATASHA_BASE: equ 390
MAPSPRITE_NATASHA_PROMO: equ 391

MAPSPRITE_AARON_BASE: equ 395
MAPSPRITE_AARON_PROMO: equ 396

MAPSPRITE_KRAID_BASE: equ 400
MAPSPRITE_KRAID_PROMO: equ 401

MAPSPRITE_DAWN_BASE: equ 405
MAPSPRITE_DAWN_PROMO: equ 406

MAPSPRITE_BILL_BASE: equ 410
MAPSPRITE_BILL_PROMO: equ 411

MAPSPRITE_THOMAS_BASE: equ 415
MAPSPRITE_THOMAS_PROMO: equ 416

MAPSPRITE_GRAHAM_BASE: equ 420
MAPSPRITE_GRAHAM_PROMO: equ 421

MAPSPRITE_ATALANTA_BASE: equ 425
MAPSPRITE_ATALANTA_PROMO: equ 426

MAPSPRITE_MARIAN_BASE: equ 430
MAPSPRITE_MARIAN_PROMO: equ 431

MAPSPRITE_RHUBY: equ 435

MAPSPRITE_ZEKE: equ 440

;MAPSPRITE_: equ 

;MAPSPRITE_: equ 

;MAPSPRITE_: equ 





MAPSPRITE_POSE1: equ 480
MAPSPRITE_BLANK: equ 481
MAPSPRITE_EFFECT1: equ 482
MAPSPRITE_RAFT: equ 483
MAPSPRITE_CARAVAN: equ 484

MAPSPRITE_OOZE: equ 500
MAPSPRITE_HUGE_RAT: equ 501
MAPSPRITE_GALAM_SOLDIER: equ 502
MAPSPRITE_GALAM_KNIGHT: equ 503
MAPSPRITE_GOBLIN: equ 504
MAPSPRITE_GREEN_OOZE: equ 505
MAPSPRITE_DARK_DWARF: equ 506
MAPSPRITE_HOBGOBLIN: equ 507
MAPSPRITE_ZOMBIE: equ 508
MAPSPRITE_GOLEM: equ 509
MAPSPRITE_SOULSOWER: equ 510
MAPSPRITE_ORC: equ 511
MAPSPRITE_BUBBLING_OOZE: equ 512
MAPSPRITE_SKELETON: equ 513
MAPSPRITE_DARK_SOLDIER: equ 514
MAPSPRITE_LIZARDMAN: equ 515
MAPSPRITE_WORM: equ 516
MAPSPRITE_DARK_KNIGHT: equ 517
MAPSPRITE_ORC_LORD: equ 518
MAPSPRITE_DEVIL_SOLDIER: equ 519
MAPSPRITE_CERBERUS: equ 520
MAPSPRITE_MUD_MAN: equ 521
MAPSPRITE_DRAGONEWT: equ 522
MAPSPRITE_PURPLE_WORM: equ 523
MAPSPRITE_EXECUTIONER: equ 524
MAPSPRITE_HELL_HOUND: equ 525
MAPSPRITE_MINOTAUR: equ 526
MAPSPRITE_CYCLOPS: equ 527
MAPSPRITE_HYDRA: equ 528
MAPSPRITE_CHAOS_WARRIOR: equ 529
MAPSPRITE_REAPER: equ 530
MAPSPRITE_EVIL_BEAST: equ 531
MAPSPRITE_PYROHYDRA: equ 532
MAPSPRITE_BLUE_DRAGON: equ 533
MAPSPRITE_RATMAN: equ 534
MAPSPRITE_MARIONETTE: equ 535
MAPSPRITE_EVIL_CLOWN: equ 536
MAPSPRITE_DULLAHAN: equ 537

MAPSPRITE_GIZMO: equ 550
MAPSPRITE_HUGE_BAT: equ 551
MAPSPRITE_VAMPIRE_BAT: equ 552
MAPSPRITE_EVIL_CLOUD: equ 553
MAPSPRITE_GARGOYLE: equ 554
MAPSPRITE_HARPY: equ 555
MAPSPRITE_LESSER_DEMON: equ 556
MAPSPRITE_WYVERN: equ 557
MAPSPRITE_HARPY_QUEEN: equ 558
MAPSPRITE_PEGASUS_KNIGHT: equ 559
MAPSPRITE_GRIFFIN: equ 560
MAPSPRITE_MIST_DEMON: equ 561
MAPSPRITE_WHITE_DRAGON: equ 562
MAPSPRITE_DEMON: equ 563
MAPSPRITE_CHAOS_DRAGON: equ 564
MAPSPRITE_DEVIL_GRIFFIN: equ 565
MAPSPRITE_ARCH_DEMON: equ 566
MAPSPRITE_CHIMERA: equ 567
MAPSPRITE_BELIAL: equ 568

MAPSPRITE_GALAM_ARCHER: equ 580
MAPSPRITE_HUNTER_GOBLIN: equ 581
MAPSPRITE_DEATH_ARCHER: equ 582
MAPSPRITE_ARROW_LAUNCHER: equ 583
MAPSPRITE_DARK_SNIPER: equ 584
MAPSPRITE_BOW_MASTER: equ 585
MAPSPRITE_BOW_RIDER: equ 586
MAPSPRITE_DARK_GUNNER: equ 587
MAPSPRITE_HORSEMAN: equ 588
MAPSPRITE_DEADEYE: equ 589

MAPSPRITE_GALAM_MAGE: equ 600
MAPSPRITE_WITCH: equ 601
MAPSPRITE_MASTER_MAGE: equ 602
MAPSPRITE_DARK_MADAM: equ 603
MAPSPRITE_WIZARD: equ 604
MAPSPRITE_NECROMANCER: equ 605
MAPSPRITE_CHAOS_WIZARD: equ 606
MAPSPRITE_DEMON_MASTER: equ 607
MAPSPRITE_SORCEROR: equ 608
MAPSPRITE_LICH: equ 609

MAPSPRITE_DARK_CLERIC: equ 620
MAPSPRITE_DEATH_MONK: equ 621
MAPSPRITE_BLACK_MONK: equ 622
MAPSPRITE_HIGH_PRIEST: equ 623
MAPSPRITE_DARK_BISHOP: equ 624
MAPSPRITE_MASTER_MONK: equ 625
MAPSPRITE_SHAMAN: equ 626
MAPSPRITE_EVIL_BISHOP: equ 627
MAPSPRITE_BLUE_SHAMAN: equ 628
MAPSPRITE_FALSE_SAINT: equ 629

MAPSPRITE_ARTILLERY: equ 640
MAPSPRITE_TORCH_EYE: equ 641
MAPSPRITE_METAL_CLAW: equ 642
MAPSPRITE_JET: equ 643

MAPSPRITE_SHELLFISH: equ 655
MAPSPRITE_MERMAID: equ 656
MAPSPRITE_CONCH: equ 657

MAPSPRITE_KRAKEN_LEG: equ 711
MAPSPRITE_KRAKEN_ARM: equ 712
MAPSPRITE_MINI_KRAKEN: equ 713
MAPSPRITE_PAWN: equ 714
MAPSPRITE_KNIGHT: equ 715
MAPSPRITE_BISHOP: equ 716
MAPSPRITE_ROOK: equ 717
MAPSPRITE_QUEEN: equ 718
MAPSPRITE_KING: equ 719
MAPSPRITE_RAT: equ 720
MAPSPRITE_WILLARD: equ 721
MAPSPRITE_MINI_TAROS: equ 722
MAPSPRITE_PRISM_FLOWER: equ 723
MAPSPRITE_BURST_ROCK: equ 724
MAPSPRITE_ZEON_GUARD: equ 725
MAPSPRITE_LASER_EYE: equ 726

MAPSPRITE_DARK_SMOKE: equ 730
MAPSPRITE_RED_BARON: equ 731
MAPSPRITE_GALAM_EVIL: equ 732
MAPSPRITE_BALBAZAK: equ 733
MAPSPRITE_RAMLADU: equ 734
MAPSPRITE_CHAOS: equ 735
MAPSPRITE_COLOSSUS: equ 736
MAPSPRITE_KANE: equ 737
MAPSPRITE_ELIOT: equ 738
MAPSPRITE_VARIOS: equ 739
MAPSPRITE_DANTON: equ 740

MAPSPRITE_ZALBARD: equ 746
MAPSPRITE_CAMEELA: equ 747
MAPSPRITE_GESHP: equ 748
MAPSPRITE_ODD_EYE: equ 749
MAPSPRITE_GALAM_ZEON: equ 750
MAPSPRITE_DARKSOL: equ 751
MAPSPRITE_MISHEALA: equ 752
MAPSPRITE_BARBARA: equ 753
MAPSPRITE_FRABELL: equ 754

MAPSPRITE_NPC_ROHDE: equ 756
MAPSPRITE_FLAME1: equ 757
MAPSPRITE_ORB: equ 758
MAPSPRITE_OBJECT1: equ 759
MAPSPRITE_POSE2: equ 760
MAPSPRITE_EFFECT2: equ 761
MAPSPRITE_POSE3: equ 762
MAPSPRITE_POSE4: equ 763
MAPSPRITE_EFFECT3: equ 764
MAPSPRITE_OBJECT2: equ 765
MAPSPRITE_OBJECT3: equ 766
MAPSPRITE_OBJECT4: equ 767
MAPSPRITE_CHICK_FLYING: equ 768
MAPSPRITE_EFFECT4: equ 769
MAPSPRITE_POSE5: equ 770
MAPSPRITE_ZELOT: equ 771
MAPSPRITE_EFFECT5: equ 772
MAPSPRITE_EFFECT6: equ 773
MAPSPRITE_DESKTOP_KING: equ 774
MAPSPRITE_HAWEL: equ 775
MAPSPRITE_BLUE_FLAME: equ 776
MAPSPRITE_PRIEST: equ 778
MAPSPRITE_PRIEST_SF1: equ 777
MAPSPRITE_SAILOR: equ 779
MAPSPRITE_MAN1: equ 780
MAPSPRITE_WOMAN1: equ 781
MAPSPRITE_MAN2: equ 782
MAPSPRITE_WOMAN2: equ 783
MAPSPRITE_MAN3: equ 784
MAPSPRITE_WOMAN3: equ 785
MAPSPRITE_BOY: equ 786
MAPSPRITE_GIRL: equ 787
MAPSPRITE_WORKER: equ 788
MAPSPRITE_GRANSEAL_KING: equ 789
MAPSPRITE_ELIS: equ 790
MAPSPRITE_MINISTER: equ 791
MAPSPRITE_SOLDIER1: equ 792
MAPSPRITE_SOLDIER2: equ 793
MAPSPRITE_MAID: equ 794
MAPSPRITE_ASTRAL: equ 795
MAPSPRITE_CAT: equ 796
MAPSPRITE_BOAT: equ 797
MAPSPRITE_CREED: equ 798
MAPSPRITE_ODDLER: equ 799
MAPSPRITE_GALAM_KING: equ 800
MAPSPRITE_MITULA: equ 801
MAPSPRITE_POSE6: equ 802
MAPSPRITE_POSE7: equ 803
MAPSPRITE_DUCK: equ 804
MAPSPRITE_FAIRY: equ 805
MAPSPRITE_BEASTMAN1: equ 806
MAPSPRITE_TURTLE: equ 807
MAPSPRITE_BEASTMAN2: equ 808
MAPSPRITE_ELF_BOY: equ 809
MAPSPRITE_ELF_GIRL: equ 810
MAPSPRITE_VIKING: equ 811
MAPSPRITE_DWARF: equ 812
MAPSPRITE_BEDOE_KING: equ 813
MAPSPRITE_BEDOE_MINISTER: equ 814
MAPSPRITE_BEDOE_SOLDIER: equ 815
MAPSPRITE_CHICK: equ 816
MAPSPRITE_PACALON_KING: equ 817
MAPSPRITE_PACALON_PRINCESS: equ 818
MAPSPRITE_PACALON_SOLDIER: equ 819
MAPSPRITE_PACALON_MAID: equ 820
MAPSPRITE_HEN: equ 821
MAPSPRITE_BIRDMAN: equ 822

MAPSPRITE_END_LIST: equ 1000

MAPSPRITE_ZEON: equ 1019
MAPSPRITE_EVIL_SPIRIT: equ 1020
MAPSPRITE_NAZCA_SHIP: equ 1021
MAPSPRITE_KRAKEN: equ 1022
MAPSPRITE_TAROS: equ 1023

; ---------------------------------------------------------------------------

; enum Mapsprites_Default
MAPSPRITE_DEFAULT: equ 0

; ---------------------------------------------------------------------------

; enum Mapsprites_Properties
MAPSPRITES_ENEMIES_START: equ $1F4
MAPSPRITES_NPCS_START: equ $2F4
MAPSPRITES_SPECIALS_START: equ $3F0
MAPSPRITES_SPECIALS_END: equ $3FF
MAPSPRITE_MASK: equ $3FF

